### ISSUE TITLE
タイムプログレス戦闘に設定しているとアクターが自動戦闘してしまいます

### ISSUE THREAD

**Issue by Awenci** [Ohisama-Craft/SRPG_GearMZ#11]
SRPGギア楽しく使わせてもらってます。
自作品ではタイムプログレス戦闘とSRPGギアを併用したいのですが
そうしようとするとアクターが自動戦闘フラグがなくても自動で動いてしまいます。
どうにかなりませんか。

**Comment by Ohisama-Craft** [comment]
SRPGギアをご利用いただき、ありがとうございます！
たしかに、その組み合わせは盲点でした。
確認して、対応策を考えてみます。

**Comment by Ohisama-Craft** [comment]
Ver.1.16Qで対応しました。

**Comment by Awenci** [comment]
対応ありがとうございます！一通り確認して問題なかったです！
これからの制作も楽しみにしています！
