### ISSUE TITLE
Issue if Screen Area is different with UI Area

### ISSUE THREAD

**Issue by RyanBram** [Ohisama-Craft/SRPG_GearMZ#12]
Hi, Takumi Ariake.
Congratulations on the release of the latest version of SRPG Gear MZ that includes AoE_Animation.

This is the release I've been waiting for the most.

There are some issues related to the latest release, especially with AoE_Animation if we set the Screen Area different from the UI Area.

1.
![Issue1](https://github.com/Ohisama-Craft/SRPG_GearMZ/assets/4508389/490aede0-3eef-4751-8544-06298f068505)
The battleback and actor/enemy home position will shift to the bottom right during the AoE Animation sideview process. The possible problem lies in how the calculation of Spriteset_Battle.prototype.createBattleField is done, because RPG Maker MV does not have this issue, but there is another issue in MV. For 1-on-1 battles, battleback and actor/enemy home positions are fine, especially after changing to `this.setHome(Graphics.boxWidth * 3 / 4 - 12 - index * 240, Graphics.boxHeight / 2 + 48)`. The actor/enemy home position issue can be solved by changing the standard X and standard Y from Graphics.width to Graphics.boxWidth as well as Graphics.height to Graphics.boxHeight. But it does not solve the battleback problem.

2.
 ![Issue2](https://github.com/Ohisama-Craft/SRPG_GearMZ/assets/4508389/92911d60-36c4-4505-96a4-c1b65d47f94c)
The same thing happens with Window_ActorCommand. If the Screen and UI areas are different, there will be times when the Window_ActorCommand appears over the edge of the screen.

**Comment by Ohisama-Craft** [comment]
Thank you, both have been addressed in Ver.1.16Q.
