### ISSUE TITLE
Skill Description

### ISSUE THREAD

**Issue by Nathan-MV** [Ohisama-Craft/SRPG_GearMZ#2]
The skill description is not displaying properly, I suppose we can fix it by showing less skills or moving the touch button to the right

![image](https://github.com/Ohisama-Craft/SRPG_GearMZ/assets/67521199/576b08e3-b103-4c95-aa1e-3de07f068311)

**Comment by Ohisama-Craft** [comment]
Thanks! I will pass this on to the English team.
